physics:
  base_mass_kg: 70.0
  watt_per_hp: 745.699872
  min_speed_mps: 0.5
  max_accel_mps2: 50.0

aero:
  sea_level_y: 64.0
  cda_base_m2: 0.70
  drag_multiplier: 1.0

gforce:
  sample_seconds: 0.2
  kill_in_creative: false
  damage_start_g: 3.0      # g at which damage begins
  damage_table:
    - { g: 3.0, dmg: 3.0 }
    - { g: 3.5, dmg: 4.5 }
    - { g: 4.0, dmg: 6.0 }
    - { g: 4.5, dmg: 7.5 }
    - { g: 5.0, dmg: 9.0 }
    - { g: 5.5, dmg: 10.5 }
    - { g: 6.0, dmg: 12.0 }
    - { g: 6.5, dmg: 13.5 }
    - { g: 7.0, dmg: 15.0 }
    - { g: 7.5, dmg: 16.5 }
    - { g: 8.0, dmg: 18.0 }
    - { g: 8.5, dmg: 19.5 }
    - { g: 9.0, dmg: 21.0 }
    - { g: 9.5, dmg: 22.5 }

fuel:
  enabled: true
  capacity: 3000
  sample_cost_per_hp: 1.0
  charge:
    coal: 1
    gunpowder: 2
    points: 300
  notify_cooldown_seconds: 2.0
  # まとめてチャージ（スニーク右クリック）
  bulk_charge_on_sneak: true      # true でスニーク右クリック時にまとめて最大までチャージ
  max_sets_per_click: 9999        # 1クリックで消費できる燃料セットの上限（安全用）

# --- Vanilla damping neutralizer (バニラ空中減衰の打ち消し) ---
vanilla:
  neutralize_drag: true          # true でバニラの空中/エリトラ減衰を相殺
  air_damping_per_tick: 0.98     # 空中の減衰係数の目安（状況で微調整）
  elytra_damping_per_tick: 0.99  # エリトラ滑空時の減衰係数の目安

life:
  enabled: true
  # 右クリック挙動
  prefer_repair_when_broken: true   # 故障中は修理を右クリックで最優先
  bulk_repair_on_sneak: true        # スニーク右クリックでまとめて修理
  max_sets_per_click: 9999          # 1クリックで修理する最大分数（安全上限）

  # 修理素材
  repair_material: LAPIS_BLOCK      # ラピスラズリブロック
  minutes_per_item: 1               # 1個あたりの修理分数

  # 案内メッセージのスパム抑制
  notify_cooldown_seconds: 2.0
