name: ElytraHorsepower
main: dev.yourname.elytrahp.ElytraHorsepower
version: 1.3.1
api-version: '1.21'
authors: ["grapelemon"]
commands:
  giveengine:
    description: Give an Elytra engine item with specified horsepower.
    usage: /giveengine <hp>
    permission: elytrahp.giveengine
permissions:
  elytrahp.giveengine:
    default: op
